### ISSUE TITLE
decoding webp failed

### ISSUE THREAD

**Issue by LarryZhao0616** [scionoftech/webp-converter#44]
Hi, I'm using dwebp() to convert .webp to .png
But I'm running into this error:

{ Error: Command failed: "/Users/xxx/node_modules/_webp-converter@2.3.1@webp-converter/bin/libwebp_osx/bin/dwebp" "/Users/xxx.webp" -o "/Users/xxx.jpg"
Decoding of /Users/xxx.webp failed.
Status: 3(BITSTREAM_ERROR)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:466:23)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 255,
  signal: null,
  cmd:
   '"/Users/xxx/_webp-converter@2.3.1@webp-converter/bin/libwebp_osx/bin/dwebp" "/Users/xxxx.webp" -o "/Users/xxxx.jpg"' }
Decoding of /Users/xxxx.webp failed.
Status: 3(BITSTREAM_ERROR)

Can anyone help me for an idea to fix this error? thx!

**Comment by Sihan0616** [comment]
for anyone who still want to convert .webp image to other format but met the same issue:

I found another worked powerful package named 'sharp'

https://sharp.pixelplumbing.com/install

```
sharp(xxx.webp).toFile(xxx.png)
```
