### ISSUE TITLE
Support for webpmux / image sequence -> animated WebP?

### ISSUE THREAD

**Issue by AdmiralPotato** [scionoftech/webp-converter#5]
I like looks of the interfaces that you've built for a most of the command line tools in the webp tool set, but I noticed a lack of support for the `webpmux` tool. Is support for this planned in any future release?

https://developers.google.com/speed/webp/docs/webpmux

**Comment by scionoftech** [comment]
hi,
Thanks for your suggestion, i have added webpmux support in webp-converter module.
